### ISSUE TITLE
ClassCast: yellow.entities.units.entity.NullEntity cannot be cast to yellow.entities.units.entity.MultiLifeUnitEntity

### ISSUE THREAD

**Issue by TimeCubed** [SMOLKEYS/yellow-rewritten#1]
I tried making a "Yellow" using a payload source, but instead it crashed my game basically as soon as it spawned. It also completely killed the save I had, but that's fine since it was an empty sandbox map anyway.

**Comment by TimeCubed** [comment]
Ghost flares don't have this issue though, they work fine.

**Comment by SMOLKEYS** [comment]
Any crash logs?

**Comment by SMOLKEYS** [comment]
Oh wait, I've actually encountered this myself before. 

Though, I sort of don't wanna fix this issue, for two reasons:
1. Yellow isn't supposed to be in payload blocks.
2. I don't know how to.

Closing for now, but will keep in mind. Use mods like Testing Utilities to spawn Yellow instead. I'll add one myself some time.

**Comment by TimeCubed** [comment]
Can you tell me how to grab that?

**Comment by SMOLKEYS** [comment]
Find it in the mod browser. It has a decent amount of popularity, so it should be somewhere around the top.
